name            = "default"
canvas          = { on = "#202020", with = "#d0d0d0"}
comment         = { on = "#202020", with = "#808080"}
constant        = { on = "#202020", with = "#d0d0d0"}
string          = { on = "#202020", with = "#548053"}
escape-seq      = { on = "#202020", with = "#4ab5a8"}
char            = { on = "#202020", with = "#d0d0d0"}
number          = { on = "#202020", with = "#be6581"}
boolean         = { on = "#202020", with = "#b2611f"}
float           = { on = "#202020", with = "#ed4076"}
identifier      = { on = "#202020", with = "#d0d0d0"}
function        = { on = "#202020", with = "#d0d0d0"}
statement       = { on = "#202020", with = "#d0d0d0"}
conditional     = { on = "#202020", with = "#d0d0d0"}
repeat          = { on = "#202020", with = "#d0d0d0"}
label           = { on = "#202020", with = "#d0d0d0"}
operator        = { on = "#202020", with = "#d0d0d0"}
keyword         = { on = "#202020", with = "#d0d0d0"}
exception       = { on = "#202020", with = "#d0d0d0"}
preproc         = { on = "#202020", with = "#d0d0d0"}
include         = { on = "#202020", with = "#d0d0d0"}
define          = { on = "#202020", with = "#d0d0d0"}
macro           = { on = "#202020", with = "#d0d0d0"}
precondit       = { on = "#202020", with = "#d0d0d0"}
type            = { on = "#202020", with = "#ff981d"}
storage-class   = { on = "#202020", with = "#d0d0d0"}
structure       = { on = "#202020", with = "#d0d0d0"}
typedef         = { on = "#202020", with = "#d0d0d0"}
special         = { on = "#202020", with = "#d0d0d0"}
special-char    = { on = "#202020", with = "#d6d700"}
tag             = { on = "#202020", with = "#d0d0d0"}
delimiter       = { on = "#202020", with = "#d0d0d0"}
special-comment = { on = "#202020", with = "#d0d0d0"}
debug           = { on = "#202020", with = "#d0d0d0"}
underline       = { on = "#202020", with = "#d0d0d0"}
ignore          = { on = "#202020", with = "#d0d0d0"}
error           = { on = "#202020", with = "#e64f4f"}
todo            = { on = "#202020", with = "#d0d0d0"}
line-nr         = { on = "#202020", with = "#86875f"}
prompt          = { on = "#202020", with = "#cf7d00"}
status-line     = { on = "#202020", with = "#cf7d00"}
tab-line        = { on = "#202020", with = "#cf7d00"}
tab-option      = { on = "#202020", with = "#cf7d00"}
tab-select      = { on = "#202020", with = "#cf7d00"}
