name            = "default"
canvas          = { on = "#373737", with = "#b9b9b9"}
comment         = { on = "#373737", with = "#ffffff"}
constant        = { on = "#373737", with = "#4e4e4e"}
string          = { on = "#373737", with = "#4e4e4e"}
char            = { on = "#373737", with = "#4e4e4e"}
number          = { on = "#373737", with = "#4e4e4e"}
boolean         = { on = "#373737", with = "#4e4e4e"}
float           = { on = "#373737", with = "#4e4e4e"}
identifier      = { on = "#373737", with = "#4e4e4e"}
function        = { on = "#373737", with = "#4e4e4e"}
statement       = { on = "#373737", with = "#4e4e4e"}
conditional     = { on = "#373737", with = "#4e4e4e"}
repeat          = { on = "#373737", with = "#4e4e4e"}
label           = { on = "#373737", with = "#4e4e4e"}
operator        = { on = "#373737", with = "#4e4e4e"}
keyword         = { on = "#373737", with = "#4e4e4e"}
exception       = { on = "#373737", with = "#4e4e4e"}
preproc         = { on = "#373737", with = "#4e4e4e"}
include         = { on = "#373737", with = "#4e4e4e"}
define          = { on = "#373737", with = "#4e4e4e"}
macro           = { on = "#373737", with = "#4e4e4e"}
precondit       = { on = "#373737", with = "#4e4e4e"}
type            = { on = "#373737", with = "#4e4e4e"}
storage-class   = { on = "#373737", with = "#4e4e4e"}
structure       = { on = "#373737", with = "#4e4e4e"}
typedef         = { on = "#373737", with = "#4e4e4e"}
special         = { on = "#373737", with = "#4e4e4e"}
special-char    = { on = "#373737", with = "#4e4e4e"}
tag             = { on = "#373737", with = "#4e4e4e"}
delimiter       = { on = "#373737", with = "#4e4e4e"}
special-comment = { on = "#373737", with = "#4e4e4e"}
debug           = { on = "#373737", with = "#4e4e4e"}
underline       = { on = "#373737", with = "#4e4e4e"}
ignore          = { on = "#373737", with = "#4e4e4e"}
error           = { on = "#373737", with = "#e64f4f"}
todo            = { on = "#373737", with = "#4e4e4e"}
line-nr         = { on = "#444444", with = "#86875f"}
prompt          = { on = "#373737", with = "#cf7d00"}
status-line     = { on = "#1c2c1c", with = "#cf7d00"}
tab-line        = { on = "#272727", with = "#cf7d00"}
tab-option      = { on = "#272727", with = "#cf7d00"}
tab-select      = { on = "#272727", with = "#cf7d00"}
