name            = "default"
canvas          = { on = 234, with = 252 }
tab             = { with = 252 }
tab-modified    = { with = 160 }
comment         = { with = 241 }
constant        = { with = 109 }
string          = { with = 142 }
escape-seq      = { with =  39 }
char            = { with = "#d0d0d0"}
number          = { with = 199 }
boolean         = { with = 201 }
float           = { with = 204}
identifier      = { with = "#d0d0d0"}
function        = { with = "#d0d0d0"}
statement       = { with = "#d0d0d0"}
conditional     = { with = "#d0d0d0"}
repeat          = { with = "#d0d0d0"}
label           = { with = "#d0d0d0"}
operator        = { with = 196 }
keyword         = { with = "#d0d0d0"}
exception       = { with = "#d0d0d0"}
preproc         = { with = "#d0d0d0"}
include         = { with = "#d0d0d0"}
define          = { with = "#d0d0d0"}
macro           = { with = "#d0d0d0"}
precondit       = { with = "#d0d0d0"}
type            = { with = 172 }
storage-class   = { with = "#d0d0d0"}
structure       = { with = 130 }
typedef         = { with = "#d0d0d0"}
special         = { with = "#d0d0d0"}
special-char    = { with = 220 }
tag             = { with = "#d0d0d0"}
delimiter       = { with = "#d0d0d0"}
special-comment = { with = "#d0d0d0"}
debug           = { with = "#d0d0d0"}
underline       = { with = "#d0d0d0"}
ignore          = { with = "#d0d0d0"}
error           = { with = "#e64f4f"}
todo            = { with = "#d0d0d0"}
line-nr         = { with = "#86875f"}
prompt          = { with = "#cf7d00"}
status-line     = { with = "#cf7d00"}
tabc-line       = { with = "#cf7d00"}
tabc-select     = { with = "#123456"}
